// <auto-generated />
using System;
using FoodDeliveryAppWA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDeliveryAppWA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryAppWA.Models.BookModel", b =>
                {
                    b.Property<int>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookId"));

                    b.Property<string>("bookAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("bookPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("bookPublisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookId");

                    b.ToTable("Book_Details");
                });

            modelBuilder.Entity("FoodDeliveryAppWA.Models.CartModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("foodId")
                        .HasColumnType("int");

                    b.Property<string>("foodImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("foodPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("foodQuantity")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cart_Details");
                });

            modelBuilder.Entity("FoodDeliveryAppWA.Models.DeliveryModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("deliveryManId")
                        .HasColumnType("int");

                    b.Property<bool>("deliveryStatus")
                        .HasColumnType("bit");

                    b.Property<string>("orderQueriesIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderQueriesOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Delivery_Details");
                });

            modelBuilder.Entity("FoodDeliveryAppWA.Models.FoodModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cookTime")
                        .HasColumnType("int");

                    b.Property<string>("foodDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("offerEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("offerPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("offerStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<string>("tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Food_Details");
                });

            modelBuilder.Entity("FoodDeliveryAppWA.Models.OrderModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("deliveryId")
                        .HasColumnType("int");

                    b.Property<int>("deliveryManId")
                        .HasColumnType("int");

                    b.Property<int>("foodId")
                        .HasColumnType("int");

                    b.Property<string>("foodImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("foodPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("foodQuantity")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Order_Details");
                });

            modelBuilder.Entity("FoodDeliveryAppWA.Models.UserModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("deliveryId")
                        .HasColumnType("int");

                    b.Property<string>("userAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("userAvailability")
                        .HasColumnType("bit");

                    b.Property<DateTime>("userDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("userNumber")
                        .HasColumnType("float");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("User_Details");
                });

            modelBuilder.Entity("YourNamespace.Models.TaskEmployeeModel", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("employeeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("employeeSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("employeeId");

                    b.ToTable("TaskTable_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
